name: CI

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm run build:chromeos --if-present
      # - run: npm run build:pime --if-present
      - run: npm run typecheck --if-present
      - run: npm run lint --if-present

  test:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:coverage
      - name: Jest Coverage Report
        if: >
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.fork == false &&
          matrix.node-version == '20.x'
        uses: ArtiomTr/jest-coverage-report-action@v2
      - name: Upload coverage reports to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

build_publish:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  permissions:
    contents: read
    pages: write
    id-token: write

  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}

  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - run: npm ci
    - run: npm run build

    - run: npx typedoc --entryPointStrategy expand ./src --exclude "**/*.test.ts"

    - run: mv docs/* output/example/
    - run: ls -la output/example | head
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: output/example
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
